name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  generate-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true # required for "git describe"

      - name: Fetch more data from git
        run: |
          # fetch everything back till the 0.11.0 tag.
          # https://stackoverflow.com/a/58082274
          git fetch --shallow-exclude 0.11.0
          git fetch --deepen=2

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0

      - name: Install PIP packages
        run: |
          pip install dataclasses_json==0.6.3 marshmallow typing-inspect semver pathspec

      - name: Generate and validate packages
        run: |
          ./tools/bundle.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: microzig-deploy/
