name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        dir:
          - all-platforms
          - raspberrypi-rp2040
          - espressif-esp
          - nxp-lpc
          # TODO: - gigadevice-gd32
          # TODO: - microchip-atmega
          # TODO: - nordic-nrf5x
          # TODO: - stmicro-stm32
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0

      - name: Build examples
        working-directory: ${{ matrix.dir }}
        run: zig build
